sonata_admin:
    title: 'Mapea Manager'
    title_logo: build/static/sigCorporativo150x150.png
    #options:
    #   use_select2:    false # disable select2
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left}
        
        groups:
            sonata_mapea:
                label: Mapea
                items:
                    - admin.mapea_core
            sonata_mapea_controls:
                label: Controls
                items:
                    - admin.mapea_control
                    - admin.mapea_control_config
                    - admin.mapea_configured_control
            sonata_mapea_plugins:
                label: Plugins
                items:
                    - admin.mapea_plugin
                    - admin.mapea_plugin_config
                    - admin.mapea_configured_plugin           
            sonata_layers:
                label: Layers
                items:
                    - admin.mapea_wmc
                    - admin.mapea_layer_wms
                    - admin.mapea_layer_wms_legend_image
                    - admin.mapea_layer_wms_map_configured
            sonata_user:
                label: User
                items:
                    - admin.user
                    - admin.group
            sonata_maps_category:
                label: "Maps Classification"
                items:
                    - admin.map_category  
                    - admin.map_sub_category  
            sonata_maps:
                label: Maps
                items:
                    - admin.mapea_map    
        
    security:
        handler: sonata.admin.security.handler.role

        role_admin: ROLE_ADMIN
        role_super_admin: ROLE_SUPER_ADMIN
      
sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
